name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Lint
      run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.16.x
          - 1.17.x
          - 1.18.x
          - ^1.18  # Latest version of Go
    name: Test with Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        check_latest: true
    - name: Test
      run: make test
