name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Lint
      run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.18.x
          - 1.19.x
    name: Test with Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
    - name: Test
      run: make test
    - name: Publish Test Coverage
      run: |
        set -ex
        go install github.com/mattn/goveralls@v0.0.11
        goveralls -coverprofile="cover.out" -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
